# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
 notify:
  webhooks:
    - url: https://outlook.office.com/webhook/6fe6ba21-9f30-427b-a6f0-6d5d4c9b2080@8ba242df-e59a-4f8b-b679-6abaf9a39135/CircleCI/fcae9ab0d0ed4ec7bb4b93dc1bf5648f/79989a05-3dfa-40c8-ad5d-e83d6a0f0a38
    
